# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 18:05
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SU', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='uploader',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='uploader',
            name='CLOSEDON',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
